name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    env:
      NEXT_PUBLIC_SUPABASE_URL: https://placeholder.supabase.co
      NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.placeholder-key-1234567890
      NEXT_PUBLIC_SITE_URL: http://127.0.0.1:3000
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type check
        run: npm run typecheck

      - name: Run unit and integration tests
        run: npm test -- --run

      - name: Build application
        run: npm run build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Run Playwright tests
        env:
          PLAYWRIGHT_BASE_URL: http://127.0.0.1:3000
        run: npm run e2e -- --reporter=line

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results/
            playwright-report/
          retention-days: 30

      - name: Analyze bundle size
        run: npm run analyze
        env:
          ANALYZE: true

      - name: Check bundle budget
        run: npm run analyze-bundle

      - name: Upload bundle analysis
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis
          path: .next/analyze
          retention-days: 30
