name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: https://xssqgtbqmyklwmxnynig.supabase.co
      NEXT_PUBLIC_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhzc3FndGJxbXlrbHdteG55bmlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MTA3NzAsImV4cCI6MjA3NjA4Njc3MH0._vMTqOwfG2NzYJQp4Cgg5-DTCwekzABHe9ZQcnTkkPA
      NEXT_PUBLIC_SUPABASE_BUCKET_LISTINGS: listing-media
      NEXT_PUBLIC_SITE_URL: https://rento-h.vercel.app
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"
      - run: pnpm i
      - run: pnpm lint
      - run: pnpm -s tsc --noEmit
      - run: pnpm build
